basePath: /
definitions:
  api.DeleteConsulKeyTop:
    properties:
      key:
        type: string
    required:
    - key
    type: object
  api.GetConsulKeyTop:
    properties:
      key:
        type: string
    required:
    - key
    type: object
  api.PutConsulKeyTop:
    properties:
      key:
        type: string
      value:
        type: object
    required:
    - key
    - value
    type: object
host: localhost:8080
info:
  contact:
    email: fancyshenmue@gmail.com
    name: Charles Hsu
  description: Consul RESTful API
  license: {}
  termsOfService: http://swagger.io/terms/
  title: Consul RESTful API
  version: "1.0"
paths:
  /api/v1/deleteKey:
    delete:
      consumes:
      - application/json
      operationId: "1"
      parameters:
      - description: body
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/api.DeleteConsulKeyTop'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete Key
      tags:
      - Delete Key
  /api/v1/getKey:
    post:
      consumes:
      - application/json
      operationId: "1"
      parameters:
      - description: body
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/api.GetConsulKeyTop'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get Key
      tags:
      - GET Key
  /api/v1/putKey:
    post:
      consumes:
      - application/json
      operationId: "1"
      parameters:
      - description: body
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/api.PutConsulKeyTop'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Put Key
      tags:
      - Put Key
swagger: "2.0"
