apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-api
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: cdn-api
          env:
            - name: MONGO_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: cdn-api-info
                  key: MONGO_ADDRESS
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: cdn-api-info
                  key: MONGO_USER
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: cdn-api-info
                  key: MONGO_PASS
            - name: MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: cdn-api-info
                  key: MONGO_DATABASE
            - name: JWT_TOKEN_HEADER
              valueFrom:
                secretKeyRef:
                  name: cdn-api-info
                  key: JWT_TOKEN_HEADER
            - name: JWT_REALM
              valueFrom:
                secretKeyRef:
                  name: cdn-api-info
                  key: JWT_REALM
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: cdn-api-info
                  key: JWT_KEY
            - name: CLOUDFLARE_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: cdn-api-info
                  key: CLOUDFLARE_AUTHKEY
            - name: CLOUDFLARE_EMAIL
              valueFrom:
                secretKeyRef:
                  name: cdn-api-info
                  key: CLOUDFLARE_EMAIL
            - name: VERIZON_CDN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cdn-api-info
                  key: VERIZON_CDN_TOKEN
            - name: VERIZON_CDN_ACCOUNT_NUMBER
              valueFrom:
                secretKeyRef:
                  name: cdn-api-info
                  key: VERIZON_CDN_ACCOUNT_NUMBER
            - name: GREYCDN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cdn-api-info
                  key: GREYCDN_TOKEN
            - name: PG_DB_USER
              valueFrom:
                secretKeyRef:
                  name: cdn-api-info
                  key: PG_DB_USER
            - name: PG_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: cdn-api-info
                  key: PG_DB_PASS
            - name: PG_DB_ADDR
              valueFrom:
                secretKeyRef:
                  name: cdn-api-info
                  key: PG_DB_ADDR
            - name: PG_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: cdn-api-info
                  key: PG_DB_PORT
            - name: PG_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cdn-api-info
                  key: PG_DB_NAME
