apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cdn-api
spec:
  rules:
  - host: dev-cdn-api.sample.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cdn-api
          servicePort: 80
